const QUERY_KEYS = {
  VOUCHER_MAIN_BANNER: 'VOUCHER_MAIN_BANNER',
  VOUCHER_LIVE_PRODUCT: 'VOUCHER_LIVE_PRODUCT',
  VOUCHER_WISH_LIST: 'VOUCHER_WISH_LIST',
  VOUCHER_SELLING_VOUCHER: 'VOUCHER_SELLING_VOUCHER',
  VOUCHER_REVIEW_LIST: 'VOUCHER_BRANDS',
  VOUCHER_THEYEYAK_WITH_BRANDS: 'VOUCHER_BRANDS',
  VOUCHER_REPLAYABLE: 'VOUCHER_REPLAYABLE',
  VOUCHER_ORDERS: 'VOUCHER_ORDERS',
  VOUCHER_RESERVATIONS: 'VOUCHER_RESERVATIONS',
  VOUCHER_BRAND_PRODUCT: 'VOUCHER_BRAND_PRODUCT',
  VOUCHER_SUBSCRIPTIONS: 'VOUCHER_SUBSCRIPTIONS',
  VOUCHER_POLICY: 'VOUCHER_POLICY',
};

export default QUERY_KEYS;
